### ISSUE TITLE
骁龙8gen2 无法安装模块，提示不支持的soc

### ISSUE THREAD

**Issue by fatinghenji** [shadow3aaa/uperf-patch#1]
不过 22 年 09 月的时候确实 8gen2 还没有发售，请问是否能提供对 8gen2 的支持呢？
![Screenshot_2023-11-30-20-46-07-91_9458954033fdd07934d2ead514062eb6](https://github.com/shadow3aaa/uperf-patch/assets/37131177/316fd77d-7730-4470-b5a1-22e61b3b1093)

**Comment by fatinghenji** [comment]
也就是说 uperf 不是一个必须的选项而是一个可选配置？

**Comment by shadow3aaa** [comment]
> 也就是说 uperf 不是一个必须的选项而是一个可选配置？

是啊，难道我没有说清楚吗，怎么会突然依赖一个不开源的项目
